Output stage to log file
theforeman/kafo pull request #267
Opened 2020-08-11 18:50 UTC by ehelms

Opening a very rough draft, not to get code review but rather to get output review. Changing from outputting the name of the logger (which provides no value to the user) to the stage results in the following look and feel:

```
[ INFO 2020-08-10T11:59:08 pre_validations] Executing hooks in group pre_migrations
[ INFO 2020-08-10T11:59:08 pre_validations] All hooks in group pre_migrations finished
[ INFO 2020-08-10T11:59:08 pre_validations] Executing hooks in group boot
[ INFO 2020-08-10T11:59:08 pre_validations] All hooks in group boot finished
[ INFO 2020-08-10T11:59:08 pre_validations] Executing hooks in group init
[ INFO 2020-08-10T11:59:08 pre_validations] All hooks in group init finished
[ INFO 2020-08-10T11:59:08 pre_validations] Loading default values from puppet modules...
[ INFO 2020-08-10T11:59:08 pre_validations] ... finished
[ INFO 2020-08-10T11:59:08 pre_validations] Executing hooks in group pre_values
[ INFO 2020-08-10T11:59:08 pre_validations] All hooks in group pre_values finished
[ INFO 2020-08-10T11:59:08 pre_validations] Running installer with args [["-v"]]
[ INFO 2020-08-10T11:59:08 pre_validations] Executing hooks in group pre_validations
[ INFO 2020-08-10T11:59:10 pre_validations] All hooks in group pre_validations finished
[ INFO 2020-08-10T11:59:10 pre_validations] Running validation checks
pre_commit
[ INFO 2020-08-10T11:59:10 pre_commit] Executing hooks in group pre_commit
[ INFO 2020-08-10T11:59:10 pre_commit] All hooks in group pre_commit finished
pre
[ INFO 2020-08-10T11:59:10 pre] Executing hooks in group pre
[ INFO 2020-08-10T11:59:10 pre] Ensuring rh-postgresql12-postgresql-server, rh-redis5-redis to package state installed
[ INFO 2020-08-10T11:59:15 pre] All hooks in group pre finished
[ INFO 2020-08-10T11:59:19 configure]  Loading facts
[ INFO 2020-08-10T11:59:19 configure]  Loading facts
[ INFO 2020-08-10T11:59:19 configure]  Loading facts
[ INFO 2020-08-10T11:59:19 configure]  Loading facts
[ INFO 2020-08-10T11:59:19 configure]  Loading facts
[ INFO 2020-08-10T11:59:19 configure]  Loading facts
[ INFO 2020-08-10T11:59:19 configure]  Loading facts
[ INFO 2020-08-10T11:59:19 configure]  Loading facts
[ INFO 2020-08-10T11:59:19 configure]  Loading facts
[ INFO 2020-08-10T11:59:19 configure]  Loading facts
[ INFO 2020-08-10T11:59:19 configure]  Loading facts
[ INFO 2020-08-10T11:59:19 configure]  Loading facts
[ WARN 2020-08-10T11:59:25 configure]  Compiled catalog for centos7.war.example.com in environment production in 3.74 seconds
[ INFO 2020-08-10T11:59:26 configure]  Applying configuration version '1597060762'
[ERROR 2020-08-10T11:59:31 configure]  Execution of '/bin/yum -d 0 -e 0 -y install foreman-postgresql' returned 1: Error: Nothing to do
[ERROR 2020-08-10T11:59:31 configure]  /Stage[main]/Foreman::Install/Package[foreman-postgresql]/ensure: change from 'purged' to 'present' failed: Execution of '/bin/yum -d 0 -e 0 -y install foreman-postgresql' returned 1: Error: Nothing to do
```

Thoughts on this? The biggest difference I can "feel" is the broken symmetry of the output.

2020-08-11 20:16 UTC, phess commented
As someone who works supporting Foreman installations, I really like the proposed change. It adds significant clarity to the logs in terms of helping pinpoint what code is running at each point.

I have to agree with @wbclark 's item 2 as I personally was unaware of https://github.com/theforeman/kafo/blob/master/doc/kafo_run.png and now I want to print it out and stick it to a nearby wall. :-)  Pairing the proposed log output with this picture will certainly improve my ability to troubleshoot installer issues.

2020-08-13 13:57 UTC, ehelms commented
I've elevated some of the inspiration here to an RFC, please add some thoughts there! https://community.theforeman.org/t/rfc-installer-output-and-logging-format/20053

2020-08-28 11:39 UTC, ekohl requested changes
More of an implementation detail: I'm worried about leaving state. This does very little to nothing for exception handling. I also really dislike that it's putting stages all over the place in all kinds of implementation details. It should really be mostly in kafo_configure.

Overall I'm very unhappy with the implementation. Carrying state in your logger system is a bad design.

My thoughts were much more around using multiple logger instances. For example, `HookContext` has a logger property. Now that's all shared but you can easily instantiate one for each hook stage (`pre_values`, `pre_commit`, etc). https://rubydoc.info/gems/logging/frames#examples has the examples. Then you don't even need to change the logging format.

I must admit I haven't tried it, but that feels like a much more robust solution.

2020-08-28 11:39 UTC, ekohl commented on lib/kafo/kafo_configure.rb
> +      Logger.setup
This feels very wrong. The config can affect the logger so you really can't initialize a logger before you have a config.

If you're keeping this, you must update the documentation. Right now it clearly states you have no logger setup before `init`.

2020-08-28 20:41 UTC, ehelms commented
Alternative implementation using loggers -- https://github.com/theforeman/kafo/pull/274

2020-09-08 20:05 UTC, closed without merging