Fixes #31304: set exit code before post hooks
theforeman/kafo pull request #307
Opened 2020-11-11 15:19 UTC by ehelms

2020-11-11 15:43 UTC, ekohl requested changes
Please explain in a commit message why this makes sense.

2020-11-12 13:23 UTC, ehelms commented
[test kafo]

2020-11-12 16:56 UTC, ehelms commented
Tests continue to fail -- proposing https://github.com/theforeman/kafo/pull/308 to address and unblock PRs

2020-11-12 21:02 UTC, ehelms commented
Failures caused by https://github.com/theforeman/foreman-infra/pull/1515

2020-11-13 13:12 UTC, ehelms commented
[test kafo]

2020-11-13 15:16 UTC, ehelms commented
[test kafo]

2020-11-13 16:47 UTC, ehelms commented
[test kafo]

2020-11-13 17:21 UTC, ehelms commented
[test kafo]

2020-11-13 17:32 UTC, ehelms commented
Jenkins is cleaned up and tests passing now, we will need this for Foreman 2.3.

2020-11-16 14:15 UTC, wbclark reviewed
Post install and upgrade hooks rely on checking `kafo.exit_code` and with this PR we now set it globally after puppet apply.

This feels like something that should have a test so that it isn't easy to break in the future?

2020-11-16 17:56 UTC, ehelms commented
[test kafo]

2020-11-16 18:08 UTC, ehelms commented
@wbclark Test added, let me know what you think.

2020-11-16 18:30 UTC, wbclark commented on test/fixtures/hooks/post/10-exit-code.rb
> +puts @kafo.exit_code
cute :)

2020-11-16 18:30 UTC, wbclark approved these changes

2020-11-16 20:17 UTC, merged