Fixes #32611: Drop Puppet 5 support
theforeman/kafo pull request #336
Opened 2021-05-17 18:52 UTC by ehelms

2021-05-17 18:53 UTC, ehelms commented
Testing update needed prior to -- https://github.com/theforeman/jenkins-jobs/pull/65

2021-05-17 20:03 UTC, ekohl requested changes
Please keep the README up to date (https://github.com/theforeman/kafo#requirements).

2021-05-17 20:03 UTC, ekohl commented on modules/kafo_configure/manifests/init.pp
> -  Boolean $add_progress = $::kafo_add_progress,
If you're dropping this, please also drop all code for it:
https://github.com/theforeman/kafo/blob/a45b1ebedda66cdf460c3fe5bfbb3696f2bd198f/lib/kafo/puppet_command.rb#L76
https://github.com/theforeman/kafo/blob/a45b1ebedda66cdf460c3fe5bfbb3696f2bd198f/lib/kafo/puppet_command.rb#L82-L84
(and the tests)

2021-05-17 20:12 UTC, ekohl commented
Also, I'd like to hold this off. Doing another major release is just a pain and we don't really gain a lot by doing so now, right?

2021-05-17 20:20 UTC, ehelms commented
> Also, I'd like to hold this off. Doing another major release is just a pain and we don't really gain a lot by doing so now, right?

If not now, then when? If we plan to drop this support, we benefit ourselves from doing it across the board and at the start of a release. The "major" bump aspect of it is pretty easy to orchestrate. What do you see as the pain ?

2021-05-18 09:02 UTC, ekohl commented
Cherry picks become more work.

2023-05-05 11:18 UTC, ekohl commented
In https://github.com/theforeman/kafo/pull/354 I went a step further and also cleaned up the progress bar support.

2023-09-22 09:03 UTC, closed without merging