Protect parsing of data types from empty lines
theforeman/kafo pull request #375
Opened 2024-08-28 11:12 UTC by lbetz

If parsing empty rows in data type files the method first returns an nil class so strip doesn't work anymore.

2024-08-28 11:58 UTC, evgeni commented
Thanks Lennart!

The rubocop failure is unrelated (fix in https://github.com/theforeman/kafo/pull/376).

Could you add a test for the empty line behaviour you're fixing?

2024-08-28 13:32 UTC, ekohl requested changes

2024-08-28 13:32 UTC, ekohl commented on lib/kafo/data_type_parser.rb
> +        line = line.split(' #').first.strip unless line.empty?
I had to check this, but what ends up happening is `''.split(' #')` returns `[]` so `[].first` is `nil`.

2024-08-28 13:32 UTC, ekohl commented on lib/kafo/data_type_parser.rb
>          next if line.start_with?('#')
I'd prefer to implement this
```suggestion
        next if line.start_with?('#') || line.empty?
```

2024-09-16 09:23 UTC, evgeni commented
Applied suggestion and added a test.

2024-09-16 09:24 UTC, bastelfreak approved these changes

2024-09-16 09:25 UTC, evgeni commented on lib/kafo/data_type_parser.rb
> +        next if line.start_with?('#') || line.empty?
This won't catch a line full of whitespace (which some editors might leave as is).
```suggestion
        next if line.start_with?('#')
        next if line.strip.empty?
```

WDYT?

2024-09-16 09:26 UTC, evgeni commented on lib/kafo/data_type_parser.rb
> +        next if line.start_with?('#') || line.empty?
oh wait, we already strip above, NVM

2024-09-16 10:22 UTC, ekohl approved these changes
Btw, long term I'd still prefer to make this depend on puppet-strings to extract the actual data types instead of attempting to maintain yet another parser. Short term this is a good fix.

2024-09-16 10:23 UTC, merged